const { LinkedList } = require('./function')

test('higher number, higher priority', () => {
  const ll = new LinkedList()
  ll.insertHead('e', 3)
  ll.insertPrio('c', 5)
  ll.insertPrio('g', 1)
  ll.insertPrio('b', 6)
  ll.insertPrio('d', 4)
  ll.insertPrio('a', 7)
  ll.insertPrio('f', 2)
  expect(ll.head.data).toMatch('a')
  expect(ll.head.next.data).toMatch('b')
  expect(ll.head.next.next.data).toMatch('c')
  expect(ll.head.next.next.next.data).toMatch('d')
  expect(ll.head.next.next.next.next.data).toMatch('e')
  expect(ll.head.next.next.next.next.next.data).toMatch('f')
  expect(ll.head.next.next.next.next.next.next.data).toMatch('g')
})
