const { LinkedList, mergeSort } = require('./function')

test('sorted', () => {
  const ll = new LinkedList()
  ll.insertHead(8)
  ll.insertLast(3)
  ll.insertLast(5)
  ll.insertLast(9)
  ll.insertLast(1)
  ll.insertLast(4)
  ll.insertLast(6)
  ll.insertLast(2)
  ll.insertLast(10)
  ll.insertLast(7)
  const result = mergeSort(ll.head)
  expect(result.data).toBe(1)
  expect(result.next.data).toBe(2)
  expect(result.next.next.data).toBe(3)
  expect(result.next.next.next.data).toBe(4)
  expect(result.next.next.next.next.data).toBe(5)
  expect(result.next.next.next.next.next.data).toBe(6)
  expect(result.next.next.next.next.next.next.data).toBe(7)
  expect(result.next.next.next.next.next.next.next.data).toBe(8)
  expect(result.next.next.next.next.next.next.next.next.data).toBe(9)
  expect(result.next.next.next.next.next.next.next.next.next.data).toBe(10)
})
